#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/prerm.d && run-parts --arg="5.3.18+" --arg="/boot/vmlinuz-5.3.18+" /etc/kernel/prerm.d
exit 0
